### ISSUE TITLE
v17.2.0 not on npmjs

### ISSUE THREAD

**Issue by godind** [angular-split/angular-split#427] opened 2024-02-17 23:32 UTC
Hi,

Not sure if this was desired but 17.2.0 is not published to npmjs.

Thanks for your great work!

**Comment by Jefiozie** [comment] 2024-02-22 11:25
Hi @godind  thanks for the headsup, I've just published it! 

[angular-split version 17.2.0](https://www.npmjs.com/package/angular-split/v/17.2.0)


If  there is anything not working anymore please let us know and file a issue.

Again thanks for the headsup! (im closing this as i think the issue is resolved)

**Closed by Jefiozie** 2024-02-22 11:25 UTC
Labels: bug
